/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MissasRouteImport } from './routes/missas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminPostagensIndexRouteImport } from './routes/_authenticated.admin.postagens.index'
import { Route as AuthenticatedAdminPostagensNovoRouteImport } from './routes/_authenticated.admin.postagens.novo'
import { Route as AuthenticatedAdminPostagensIdRouteImport } from './routes/_authenticated.admin.postagens.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MissasRoute = MissasRouteImport.update({
  id: '/missas',
  path: '/missas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPostagensIndexRoute =
  AuthenticatedAdminPostagensIndexRouteImport.update({
    id: '/postagens/',
    path: '/postagens/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostagensNovoRoute =
  AuthenticatedAdminPostagensNovoRouteImport.update({
    id: '/postagens/novo',
    path: '/postagens/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostagensIdRoute =
  AuthenticatedAdminPostagensIdRouteImport.update({
    id: '/postagens/$id',
    path: '/postagens/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/missas': typeof MissasRoute
  '/newsletter': typeof NewsletterRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/postagens/$id': typeof AuthenticatedAdminPostagensIdRoute
  '/admin/postagens/novo': typeof AuthenticatedAdminPostagensNovoRoute
  '/admin/postagens/': typeof AuthenticatedAdminPostagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/missas': typeof MissasRoute
  '/newsletter': typeof NewsletterRoute
  '/sobre': typeof SobreRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias': typeof NoticiasIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/postagens/$id': typeof AuthenticatedAdminPostagensIdRoute
  '/admin/postagens/novo': typeof AuthenticatedAdminPostagensNovoRoute
  '/admin/postagens': typeof AuthenticatedAdminPostagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/missas': typeof MissasRoute
  '/newsletter': typeof NewsletterRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/postagens/$id': typeof AuthenticatedAdminPostagensIdRoute
  '/_authenticated/admin/postagens/novo': typeof AuthenticatedAdminPostagensNovoRoute
  '/_authenticated/admin/postagens/': typeof AuthenticatedAdminPostagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/contato'
    | '/galeria'
    | '/missas'
    | '/newsletter'
    | '/sobre'
    | '/admin'
    | '/noticias/$slug'
    | '/noticias/'
    | '/admin/'
    | '/admin/postagens/$id'
    | '/admin/postagens/novo'
    | '/admin/postagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/contato'
    | '/galeria'
    | '/missas'
    | '/newsletter'
    | '/sobre'
    | '/noticias/$slug'
    | '/noticias'
    | '/admin'
    | '/admin/postagens/$id'
    | '/admin/postagens/novo'
    | '/admin/postagens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/auth'
    | '/contato'
    | '/galeria'
    | '/missas'
    | '/newsletter'
    | '/sobre'
    | '/_authenticated/admin'
    | '/noticias/$slug'
    | '/noticias/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/postagens/$id'
    | '/_authenticated/admin/postagens/novo'
    | '/_authenticated/admin/postagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  MissasRoute: typeof MissasRoute
  NewsletterRoute: typeof NewsletterRoute
  SobreRoute: typeof SobreRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missas': {
      id: '/missas'
      path: '/missas'
      fullPath: '/missas'
      preLoaderRoute: typeof MissasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/postagens/': {
      id: '/_authenticated/admin/postagens/'
      path: '/postagens'
      fullPath: '/admin/postagens/'
      preLoaderRoute: typeof AuthenticatedAdminPostagensIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/postagens/novo': {
      id: '/_authenticated/admin/postagens/novo'
      path: '/postagens/novo'
      fullPath: '/admin/postagens/novo'
      preLoaderRoute: typeof AuthenticatedAdminPostagensNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/postagens/$id': {
      id: '/_authenticated/admin/postagens/$id'
      path: '/postagens/$id'
      fullPath: '/admin/postagens/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostagensIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPostagensIdRoute: typeof AuthenticatedAdminPostagensIdRoute
  AuthenticatedAdminPostagensNovoRoute: typeof AuthenticatedAdminPostagensNovoRoute
  AuthenticatedAdminPostagensIndexRoute: typeof AuthenticatedAdminPostagensIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPostagensIdRoute: AuthenticatedAdminPostagensIdRoute,
  AuthenticatedAdminPostagensNovoRoute: AuthenticatedAdminPostagensNovoRoute,
  AuthenticatedAdminPostagensIndexRoute: AuthenticatedAdminPostagensIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  MissasRoute: MissasRoute,
  NewsletterRoute: NewsletterRoute,
  SobreRoute: SobreRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
